### **Matrices**

Hay un tipo muy utilizado de listas anidadas. Se caracteriza por ser una lista de $m$ listas, donde cada una de las listas tiene el mismo número de elementos, $n$. A este tipo de listas se les conoce como matrices.

In [1]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

En matemáticas, las matrices se definen del siguiente modo.

**Matriz.** Una matriz de dimensiones $m\times n$ es una tabla formada por elementos dispuestos en $m$ filas y $n$ columnas de la forma

$$A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\end{pmatrix}$$

Los elementos de la matriz se representan con doble subíndice, $a_{ij}$, donde el primero indica la fila a la que pertenece y, el segundo, la columna.

Entonces, la matriz que hemos definido anteriormente

In [2]:
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Escrita en forma de tabla sería: `matrix` $= \displaystyle\begin{pmatrix} 1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9\end{pmatrix}$

Para acceder a los elementos de una matriz en `Python`, utilizamos la sintaxis `[][]`, donde primero indicamos la fila y, a continuación, la columna

In [3]:
# Podemos acceder a todos los elementos de la matrix recorriéndola
for row in matrix:
    print(row)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [4]:
# Obteniendo los elementos y subelementos
for row in matrix: # Accedemos a las filas de la matrix
    for element in row: # Accedemos a los elementos de las filas
        print(element, end=' ')

1 2 3 4 5 6 7 8 9 

In [5]:
# 1. Recorriendo por posición (índice)
m = len(matrix) # Filas
n = len(matrix[0]) # Columnas

for row in range(m):
    for column in range(n):
        print(matrix[row][column], end=' ')
    print('')

print()

# 2. Recorriendo por elemento
for row in matrix:
    for element in row:
        print(element, end=' ')
    print('')

1 2 3 
4 5 6 
7 8 9 

1 2 3 
4 5 6 
7 8 9 


#### **Suma de matrices**

Para poder sumar dos matrices, necesitamos que tengan la misma dimensión. Entonces, dadas $A$ y $B$ dos matrices con dimensión $m\times n$, su suma será una matriz de dimensión $m\times n$ y sus elementos se obtienen del siguiente modo:

$$\begin{array}{lll}A + B &=& (a_{ij})_{m\times n} + (b_{ij})_{m\times n} = (a_{ij} + b_{ij})_{m\times n}\\ 
&=&\begin{pmatrix} 
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\\
\end{pmatrix} + \begin{pmatrix} 
b_{11} &b_{12} & \cdots &b_{1n}\\
b_{21} &b_{22} & \cdots &b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
b_{m1} &b_{m2} & \cdots & b_{mn}\\
\end{pmatrix} = \begin{pmatrix} 
a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n}\\
a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn}\\
\end{pmatrix}
\end{array}$$

Dadas dos matrices con la misma dimensión, las podemos usar haciendo uso de bucles `for` anidados.

In [6]:
# Matrices
A = [[1, 0, -3], [2, 0, 1], [-1, -1, 0]]
B = [[-1, -2, 0], [-2, 3, 0], [0, 0, -3]]

# Hallamos las filas y columnas
m = len(A) # Filas
n = len(A[0]) # Columnas

# Si el número de filas y columnas coinciden en ambas matrices
try: 
  len(A) == len(B) and len(A[0]) == len(B[0])
  
  # Procedimiento
  C = list()
  for i in range(m):
    C.append(list())
    for j in range(n):
      C[i].append(A[i][j] + B[i][j])

  print(f'Matriz resultante: {C}')

except IndexError:
    print('Erorr en las dimensiones de las matrices')

except Exception as e:
    print(f'No se puede realizar la suma, tenemos un error de tipo: {type(e).__name__}')

Matriz resultante: [[0, -2, -3], [0, 3, 1], [-1, -1, -3]]


El resultado de sumar las matrices $A$ y $B$ ha sido:

$$\begin{pmatrix}
1 & 0 & -3\\
2 & 0 & 1\\
-1 & -1 & 0\end{pmatrix} + \begin{pmatrix}
-1 & -2 & 0\\
-2 & -3 & 0\\
0 & 0 & -3\end{pmatrix} = 
\begin{pmatrix}
0 & -2 & -3\\
0 & -3 & 1\\
-1 & -1 & -3\end{pmatrix}$$

In [7]:
# Recorremos la matriz resultante
for row in C:
    print(row)

[0, -2, -3]
[0, 3, 1]
[-1, -1, -3]


**Observación** Hemos puesto un `try` que, suponiendo que tanto $A$ como $B$ son matrices, prueba si sus dimensiones coinciden. De ser cierto, procede a hacer la suma. De lo contrario, nos arroja una excepción indicando que la suma no puede llevarse a cabo.

#### **Producto de matrices**

Para poder multiplicar matrices, necesitamos que la matriz de la izquierda tenga el mismo número de columnas que número de filas tiene la matriz de la derecha. Entonces, dadas las matrices $A$ y $B$ de dimensiones $m\times n$ y $n\times p$ respectivamente, su producto será una matriz de dimensión $m\times p$ y se obtiene del siguiente modo:

$$\begin{array}{lll}A\cdot B &=& (a_{ij})_{m\times n}\cdot (b_{ij})_{n\times p} = \left(\sum_{k = 1}^n a_{ik}\cdot b_{kj}\right)_{m\times p}\\
&=& \begin{pmatrix} 
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\\
\end{pmatrix} \cdot \begin{pmatrix} 
b_{11} &b_{12} & \cdots &b_{1p}\\
b_{21} &b_{22} & \cdots &b_{2p}\\
\vdots & \vdots & \ddots & \vdots\\
b_{n1} &b_{n2} & \cdots & b_{np}\\
\end{pmatrix} = \begin{pmatrix} 
a_{11}\cdot b_{11} + a_{12} \cdot b_{21} + \cdots + a_{1n}\cdot b_{n1} & \sum_{k = 1}^n a_{1k}\cdot b_{k2} & \cdots & \sum_{k = 1}^n a_{1k}\cdot b_{kp}\\
a_{21}\cdot b_{11} + a_{22} \cdot b_{21} + \cdots + a_{2n}\cdot b_{n1} & \sum_{k = 1}^n a_{2k}\cdot b_{k2} & \cdots & \sum_{k = 1}^n a_{2k}\cdot b_{kp}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1}\cdot b_{11} + a_{m2} \cdot b_{21} + \cdots + a_{mn}\cdot b_{n1} & \sum_{k = 1}^n a_{mk}\cdot b_{k2} & \cdots & \sum_{k = 1}^n a_{mk}\cdot b_{kp}
\end{pmatrix}\end{array}$$

Dadas dos matrices, la primera con el mismo número de columnas que filas tiene la segunda, podemos multiplicarlas del siguiente modo:

In [8]:
# Matrices
A = [[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]]
B = [[-1, -2, 0], [-2, 3, 0], [0, 0, -3], [1, 1, -1]]

# Dimensiones
m, n, p, q = len(A), len(B), len(B[0]), len(A[0])

""" 
    Propiedades:
    m => Número de filas de A
    n => Número de filas de B
    p => Número de columnas de B
    q => Número de columnas de A
"""

try:
  # Deben coincidir el número de filas de A con el número de columnas de B
  m == p or n == q

  # Procedimiento
  C = list()
  for i in range(m):
    C.append(list())
    for j in range(p):
      elemento = 0
      for k in range(n):
        elemento = elemento + A[i][k] * B[k][j]
      C[i].append(elemento)
  
  print(f'Matriz resultante: {C}')

except IndexError:
    print('Erorr en las dimensiones de las matrices')

except Exception as e:
  print(f'No se puede realizar el producto de matrices, tenemos un error de tipo: {type(e).__name__} ')

Matriz resultante: [[1, 0, 7], [-1, -3, -4], [1, 2, 3]]


El resultado de multiplicar las matrices $A$ y $B$ ha sido:

$$\begin{array}{lll} A\cdot B &=& 
\begin{pmatrix}
1 & 0 & -3 & 2\\
2 & 0 & 1 & 1\\
-1 & 0 & -1 & 0
\end{pmatrix}\cdot\begin{pmatrix}
-1 & -2 & 0\\
-2 & 3 & 0\\
0 & 0 & -3\\
1 & 1 & -1
\end{pmatrix}\\ &=& \begin{pmatrix}
1\cdot (-1) + 0\cdot (-2) -3\cdot 0 + 2\cdot 1 & 1\cdot (-2) + 0\cdot 3 -3\cdot 0 + 2\cdot 1 & 1\cdot 0 + 0\cdot 0 -3\cdot (-3) + 2\cdot (-1)\\
2\cdot (-1) + 0\cdot (-2) + 1\cdot 0 + 1\cdot 1  & 2\cdot (-2) + 0\cdot 3 + 1\cdot 0 + 1\cdot 1 & 2\cdot 0 + 0\cdot 0 + 1\cdot (-3) + 1\cdot (-1)\\
-1\cdot (-1) + 0\cdot (-2) -1\cdot 0 + 0\cdot 1  & -1\cdot (-2) + 0\cdot 3 -1\cdot 0 + 0\cdot 1 & -1\cdot 0 + 0\cdot 0 -1\cdot (-3) + 0\cdot (-1)
\end{pmatrix}\\ &=& \begin{pmatrix}
1 & 0 & 7\\
-1 & -3 & -4\\
1 & 2 & 3
\end{pmatrix}
\end{array}$$

In [9]:
# Recorremos la matriz resultante
for row in C:
    print(row)

[1, 0, 7]
[-1, -3, -4]
[1, 2, 3]


#### **Matrices con `numpy`**

Existe una forma más sencilla de trabajar con matrices y es gracias a la librería `numpy`. Para importarla, simplemente hay que ejecutar la siguiente línea de código.

Podemos crear matrices de numpy a partir de listas con el método `.matrix()`

In [10]:
# Numpy
import numpy as np

M = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
print(M)

[[ 1  0 -3  2]
 [ 2  0  1  1]
 [-1  0 -1  0]]


Ahora es más sencillo sumar matrices, pues solamente necesitamos el operador `+`

In [11]:
A = np.matrix([[1, 0, -3], [2, 0, 1], [-1, -1, 0]])
B = np.matrix([[-1, -2, 0], [-2, 3, 0], [0, 0, -3]])
matrix_sum = A + B
print(matrix_sum)

[[ 0 -2 -3]
 [ 0  3  1]
 [-1 -1 -3]]


También es más sencillo hacer el producto matricial $A\cdot B$ con el método `.dot()` o bien utilizar el `@` como símbolo de operador de multiplicación

In [12]:
A = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
B = np.matrix([[-1, -2, 0], [-2, 3, 0], [0, 0, -3], [1, 1, -1]])

matrix_prod = A.dot(B)
print(matrix_prod)

[[ 1  0  7]
 [-1 -3 -4]
 [ 1  2  3]]


In [13]:
# Otra manera
A = np.matrix([[1, 0, -3, 2], [2, 0, 1, 1], [-1, 0, -1, 0]])
B = np.matrix([[-1, -2, 0], [-2, 3, 0], [0, 0, -3], [1, 1, -1]])

matrix_prod = A@B
print(matrix_prod)

[[ 1  0  7]
 [-1 -3 -4]
 [ 1  2  3]]
